### ISSUE TITLE
minSdkVersion and targetSdkVersion

### ISSUE THREAD

**Issue by DanielNogueiraAndroid** [googlesamples/android-GridViewPager#2]
Is the best way to organise a minSdkVersion and targetSdkVersion?
please look at the files build.gradle and AndroidManifest.xml: 

android-GridViewPager/Wearable/build.gradle
        minSdkVersion 24
        targetSdkVersion 22

android-GridViewPager/Wearable/src/main/AndroidManifest.xml        
    <uses-sdk android:minSdkVersion="20"
              android:targetSdkVersion="22" />

**Comment by codingjeremy** [comment]
Thanks for the catch! You are correct, that is not correct. I will make sure it is fixed in the next push.

**Comment by codingjeremy** [comment]
Fixed.
